#!/bin/bash
#include <stdio>
/*a C program that prints exactly "Programming is like building a multilingual puzzle, followed by a new line*/

int puts(void)
{
	write(""Programming is like building a multilingual puzzle\n");
	return 0;
}
